services:
  fastapi:
    build: 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/fastapi_db
      - MONGO_URL=mongodb://mongo:27017
    volumes:
      - .:/app  # Mount current directory for live changes (optional)

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
